export const SEARCH_INPUT_VALUE_CHANGE = 'SEARCH_INPUT_VALUE_CHANGE';
export const SEARCH_INPUT_VALUE_CHANGE_SUCCESS = 'SEARCH_INPUT_VALUE_CHANGE_SUCCESS';
export const SEARCH_INPUT_VALUE_CHANGE_LOADING = 'SEARCH_INPUT_VALUE_CHANGE_LOADING';
export const SEARCH_INPUT_VALUE_CHANGE_ERROR = 'SEARCH_INPUT_VALUE_CHANGE_ERROR';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR';
export const SAVE_USER_LOADING = 'SAVE_USER_LOADING';

export const LOGIN = 'LOGIN';
