export const SEARCH_INPUT_VALUE_CHANGE = "SEARCH_INPUT_VALUE_CHANGE";
export const SEARCH_INPUT_VALUE_CHANGE_SUCCESS = "SEARCH_INPUT_VALUE_CHANGE_SUCCESS";
export const SEARCH_INPUT_VALUE_CHANGE_LOADING = "SEARCH_INPUT_VALUE_CHANGE_LOADING";
export const SEARCH_INPUT_VALUE_CHANGE_ERROR = "SEARCH_INPUT_VALUE_CHANGE_ERROR";